/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArtistPageResponse = IDL.Record({
  'bio' : IDL.Text,
  'postCount' : IDL.Nat,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : Time,
  'tier' : IDL.Text,
  'bandName' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'genre' : IDL.Text,
  'musicLinks' : IDL.Vec(IDL.Text),
  'followerCount' : IDL.Nat,
  'headerImageHash' : IDL.Opt(ExternalBlob),
  'followingCount' : IDL.Nat,
  'isFollowedByCurrentUser' : IDL.Bool,
  'profilePictureHash' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Time,
  'website' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'headerImageHash' : IDL.Opt(ExternalBlob),
  'profilePictureHash' : IDL.Opt(ExternalBlob),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createOrUpdateArtistPage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getArtistPage' : IDL.Func([], [IDL.Opt(ArtistPageResponse)], ['query']),
  'getArtistPageByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ArtistPageResponse)],
      ['query'],
    ),
  'getArtistPageByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ArtistPageResponse)],
      ['query'],
    ),
  'getPrincipalByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'setProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateArtistHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateArtistProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArtistPageResponse = IDL.Record({
    'bio' : IDL.Text,
    'postCount' : IDL.Nat,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : Time,
    'tier' : IDL.Text,
    'bandName' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'genre' : IDL.Text,
    'musicLinks' : IDL.Vec(IDL.Text),
    'followerCount' : IDL.Nat,
    'headerImageHash' : IDL.Opt(ExternalBlob),
    'followingCount' : IDL.Nat,
    'isFollowedByCurrentUser' : IDL.Bool,
    'profilePictureHash' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Time,
    'website' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'headerImageHash' : IDL.Opt(ExternalBlob),
    'profilePictureHash' : IDL.Opt(ExternalBlob),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createOrUpdateArtistPage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getArtistPage' : IDL.Func([], [IDL.Opt(ArtistPageResponse)], ['query']),
    'getArtistPageByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ArtistPageResponse)],
        ['query'],
      ),
    'getArtistPageByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ArtistPageResponse)],
        ['query'],
      ),
    'getPrincipalByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateArtistHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateArtistProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateHeaderImage' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Opt(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };