/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistPageResponse {
  'bio' : string,
  'postCount' : bigint,
  'principal' : Principal,
  'username' : string,
  'createdAt' : Time,
  'tier' : string,
  'bandName' : string,
  'website' : [] | [string],
  'updatedAt' : Time,
  'genre' : string,
  'musicLinks' : Array<string>,
  'followerCount' : bigint,
  'headerImageHash' : [] | [ExternalBlob],
  'followingCount' : bigint,
  'isFollowedByCurrentUser' : boolean,
  'profilePictureHash' : [] | [ExternalBlob],
  'location' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : Time,
  'website' : [] | [string],
  'updatedAt' : Time,
  'headerImageHash' : [] | [ExternalBlob],
  'profilePictureHash' : [] | [ExternalBlob],
  'location' : [] | [string],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createOrUpdateArtistPage' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<string>,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'getArtistPage' : ActorMethod<[], [] | [ArtistPageResponse]>,
  'getArtistPageByPrincipal' : ActorMethod<
    [Principal],
    [] | [ArtistPageResponse]
  >,
  'getArtistPageByUsername' : ActorMethod<[string], [] | [ArtistPageResponse]>,
  'getPrincipalByUsername' : ActorMethod<[string], [] | [Principal]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'setProfile' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateArtistHeaderImage' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateArtistProfilePicture' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateHeaderImage' : ActorMethod<[[] | [ExternalBlob]], undefined>,
  'updateProfilePicture' : ActorMethod<[[] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];